feat: add notebook for submitting civic assertions via prod api
ga4gh/gks2clinvar pull request #13
Opened 2024-05-28 23:06 UTC by korikuzma

close #12

Probably didn't need a PR, but thought I'd save work.

2024-05-28 23:15 UTC, korikuzma commented
Oh interesting. Both submissions had errors on prod, but passed the test/prod api dry runs. All errors are due to `ClinicalSignificance.citation`. Error messages look as follows:

> "PubMed:25265492;PubMed:23020132;PubMed:28891408;PubMed:25399551;https://civicdb.org/links/evidence/6178;https://civicdb.org/links/evidence/6938;https://civicdb.org/links/evidence/3758;https://civicdb.org/links/evidence/6940 is an invalid citation. Please check both the name of the database and the identifier from that database"

2024-05-29 17:31 UTC, larrybabb approved these changes
I'm not sure what all this is. But I approve. 😁

2024-06-11 15:30 UTC, korikuzma commented
@larrybabb @ahwagner SCV005045671 and SCV005045669 are now viewable on the ClinVar UI

2024-06-21 17:30 UTC, ahwagner commented
Looking at this, it appears that there are some slight differences between the automated and manual submissions: 
![image](https://github.com/ga4gh/gks-clinvar/assets/811065/e05b2c75-f8b0-498f-842a-b3a580a6d23c)

![image](https://github.com/ga4gh/gks-clinvar/assets/811065/7a982576-b3f5-4a31-a04a-1e205686f5c2)

Primarily 1) links to the associated CIViC AID and EID records and 2) link to the appropriate method for each assertion type.

2024-06-21 17:31 UTC, ahwagner requested changes
See https://github.com/ga4gh/gks-clinvar/pull/13#issuecomment-2183158940

2024-06-21 20:45 UTC, korikuzma commented
> Primarily 1) links to the associated CIViC AID and EID records 

@ahwagner see [this](https://github.com/ga4gh/gks-clinvar/issues/12#issuecomment-2136254051) comment and the following comment. I had trouble submitting CIViC URLs

2024-06-21 20:46 UTC, korikuzma commented
> 2) link to the appropriate method for each assertion type.

@ahwagner Hm. I will look into this later.

2024-06-24 12:10 UTC, korikuzma commented
@ahwagner I am going to email the ClinVar team to see if there is a way to include this information using the API or if it's not supported yet.

2024-06-29 00:51 UTC, korikuzma commented
> @ahwagner I am going to email the ClinVar team to see if there is a way to include this information using the API or if it's not supported yet.

@ahwagner I emailed giving them examples of citations with URLs (including the [germline test submission](https://github.com/ncbi/clinvar/blob/master/submission_api_schema/sample_api_submissions/sample_germline_hgvs_submission.json)) with failures. They confirmed URLs are not working with the API but that the development team is discussing and will get back to us. 

I’ve submitted an update to include guideline PMID and hoping it shows in the UI soon.

2024-07-01 11:32 UTC, korikuzma commented
SCV005045669 link to guidelines has been updated (added `assertionCriteria`). Still waiting on onco to be updated. 
![Screenshot 2024-07-01 at 07 31 28](https://github.com/ga4gh/gks-clinvar/assets/42851808/5a711027-7669-4766-9fd9-c7947e59718c)

2024-07-05 15:07 UTC, korikuzma commented
> @ahwagner I emailed giving them examples of citations with URLs (including the [germline test submission](https://github.com/ncbi/clinvar/blob/master/submission_api_schema/sample_api_submissions/sample_germline_hgvs_submission.json)) with failures. They confirmed URLs are not working with the API but that the development team is discussing and will get back to us.

They confirmed it is a bug and will let us know when it is fixed.

2025-03-18 14:45 UTC, ahwagner approved these changes

2025-03-18 16:31 UTC, merged